services:
  - type: web
    name: agristack-bandipora
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 60
    envVars:
      - key: DOWNLOAD_PASSWORD
        sync: false
